<div class="page-header">
    <h2>Editar Tipo de Produto</h2>
</div>

<div class="col-lg-3">
    <ul class="nav nav-pills nav-stacked">
        <li><?= link_to($product_types_index_path(), 'Lista de Tipos de produtos'); ?></li>
        <li><?= link_to($product_types_destroy_path($type->id->getValue()), 'Excluir', 'data-confirm="Tem certeza?"'); ?></li>
    </ul>
</div>

<div class="col-lg-7">

    <form role="form" action="<?=url_for($product_types_edit_path($type->id->getValue()))?>" method="POST">

        <?=text_area($type->description, array('name'=>'type', 'title'=>'Descrição', 'placeholder'=>'Descrição')); ?>

        <button type="submit" class="btn btn-primary"> Confirmar</button>
    </form>

</div>