<div class="page-header">
    <h2>Tipo de Produto</h2>
</div>

<div class="col-lg-3">
    <ul class="nav nav-pills nav-stacked">
        <li><?= link_to($product_types_index_path(), 'Lista de Tipos de Produto'); ?></li>
        <li><?= link_to($product_types_fresh_path(), 'Novo Tipo de Produto'); ?></li>
        <li><?= link_to($product_types_edit_path($type->id->getValue()), 'Editar'); ?></li>
        <li><?= link_to($product_types_destroy_path($type->id->getValue()), 'Excluir', 'data-confirm="Tem certeza?"'); ?></li>
    </ul>
</div>

<div class="col-lg-7">

    <table class="table">
        <tr>
            <td class="col-lg-3"><b>Criado em:</b></td>
            <td><?= format_date($type->created_at->getValue()); ?></td>
        </tr>
        <td><b>Descrição:</b></td>
        <td><?= $type->description->getValue(); ?></td>
        </tr>
    </table>
</div>