<div class="page-header" id="page-title">
    <h1>Serviços</h1>
    <i>Últimos serviços</i>
</div>

<div class="col-lg-3">
    <ul class="nav nav-pills nav-stacked">
        <li><?= link_to($accommodations_index_path(), "Hóspedes <span class='badge'>{$this->countAccommodations}</span>"); ?></li>
    </ul>
</div>

<div class="col-lg-8">
    <table class="table table-bordered table-hover">
        <thead>
            <th>Hospedagem (Cód. Controle)</th>
            <th>Tipo de serviço</th>
            <th>Data</th>
            <th>Ação</th>
        </thead>
        <?php
        if ($this->services):
            foreach ($this->services as $service): ?>

                <tr>
                    <td>
                        <?=link_to($accommodations_show_path($service['accommodation_id']),
                            $service['control']); ?>
                    </td>
                    <td>
                        <?=link_to($service_types_show_path($service['service_type_id']),
                            $service['service_type_description']); ?>
                    </td>
                    <td><?= format_date($service['created_at'],'d/m/Y H:i:s'); ?></td>
                    <td class="col-md-3">
                        <?= link_to($services_show_path($service['id']), 'ver'); ?>|
                        <?= link_to($services_destroy_path($service['id']), 'cancelar', 'data-confirm="Tem certeza?"'); ?>
                    </td>
                </tr>

            <?php
            endforeach; else: ?>
            <tr>
                <td colspan="5"><span class="label label-info">Nenhum registro encontrado!</span></td>
            </tr>
        <?php endif; ?>
        <tfoot>
            <td colspan="5">Mostrando últimos 20 serviços</td>
        </tfoot>
    </table>
</div>