<div class="page-header" id="page-title">
    <h2>Editar Funcionário</h2>
</div>

<div class="col-lg-3">
    <ul class="nav nav-pills nav-stacked">
        <li><?= link_to($employees_index_path(), 'Lista de Funcionários'); ?></li>
        <li><?= link_to($employees_destroy_path($this->employee->id->getValue()), 'Excluir', 'data-confirm="Tem certeza?"'); ?></li>
        <li><?= link_to($employees_reset_password_path($this->employee->id->getValue()), 'Restabelecer senha', 'data-confirm="Tem certeza?"'); ?></li>
    </ul>
</div>

<div class="col-lg-7">

    <form role="form" action="<?=$employees_update_path($this->employee->id->getValue())?>" method="POST">

        <?=text_field($this->employee->name, array('name'=>'employee', 'title'=>'Nome', 'placeholder'=>'Nome...')); ?>
        <?=text_field($this->employee->login, array('name'=>'employee', 'title'=>'E-mail', 'placeholder' => 'email@servidor.com')); ?>
        <?=select($this->employee->level, $this->levels,
            array('name'=>'employee', 'title'=>'Perfil'),$this->employee->level->getValue()); ?>

        <button type="submit" class="btn btn-primary"> Confirmar</button>
    </form>

</div>