<div class="page-header" id="page-title">
    <h2>Editar Tipo de Serviço</h2>
</div>

<div class="col-lg-3">
    <ul class="nav nav-pills nav-stacked">
        <li><?= link_to($service_types_index_path(), 'Lista de Tipos de serviços'); ?></li>
        <li><?= link_to($service_types_destroy_path($this->type->id->getValue()), 'Excluir', 'data-confirm="Tem certeza?"'); ?></li>
    </ul>
</div>

<div class="col-lg-7">

    <form role="form" action="<?=$service_types_edit_path($this->type->id->getValue())?>" method="POST">

        <?=text_area($this->type->description, array('name'=>'type', 'title'=>'Descrição', 'placeholder'=>'Descrição')); ?>

        <button type="submit" class="btn btn-primary"> Confirmar</button>
    </form>

</div>