<div class="page-header">
    <h1>Tipos de Serviço</h1>
</div>

<div class="col-lg-3">
    <ul class="nav nav-pills nav-stacked">
        <li><?= link_to($services_index_path(), 'Lista de Serviços'); ?></li>
        <li><?= link_to($service_types_fresh_path(), 'Novo Tipo de serviço'); ?></li>
    </ul>
</div>

<div class="col-lg-7">
    <table class="table table-bordered">
        <tr>
            <th>#</th>
            <th>Descrição</th>
            <th>Ação</th>
        </tr>
        <?php
        $n = 1;
        if ($this->types):
            foreach ($this->types as $type): ?>

                <tr>
                    <td><?= $n; ?></td>
                    <td><?= $type['description']; ?></td>
                    <td class="col-md-3">
                        <?= link_to( $service_types_show_path($type['id']), 'ver'); ?>|
                        <?= link_to( $service_types_edit_path($type['id']), 'editar'); ?>|
                        <?= link_to( $service_types_destroy_path($type['id']), 'remover','data-confirm="Tem certeza?"'); ?>
                    </td>
                </tr>

                <?php
                $n++;
            endforeach; else: ?>
            <tr>
                <td colspan="3"><span class="label label-info">Nenhum registro encontrado!</span></td>
            </tr>
        <?php endif; ?>
    </table>
</div>
