<div class="page-header">
    <h2>Tipo de Serviço</h2>
</div>

<div class="col-lg-3">
    <ul class="nav nav-pills nav-stacked">
        <li><?= link_to($service_types_index_path(), 'Lista de Tipos de Serviço'); ?></li>
        <li><?= link_to($service_types_fresh_path(), 'Novo Tipo de Serviço'); ?></li>
        <li><?= link_to($service_types_edit_path($this->type->id->getValue()), 'Editar'); ?></li>
        <li><?= link_to($service_types_destroy_path($this->type->id->getValue()), 'Excluir', 'data-confirm="Tem certeza?"'); ?></li>
    </ul>
</div>

<div class="col-lg-7">


    <h4>Criado em:</h4>
    <p><?=format_date($this->type->created_at->getValue()); ?></p>

    <h4>Descrição:</h4>
    <p><?=$this->type->description->getValue(); ?></p>

</div>