<div class="page-header" id="page-title">
    <h1>Hospedagens - histórico</h1>
</div>

<div class="col-lg-3">
    <ul class="nav nav-pills nav-stacked">
        <li><?= link_to($accommodations_index_path(), "Hóspedes <span class='badge'>{$this->countAccommodations}</span>"); ?></li>
    </ul>
</div>

<div class="col-lg-8">

    <form method="POST" action="<?= $accommodations_history_path(); ?>">
        <div class="row">
            <div class="col-lg-12">
                <input type="text" class="form-control" name="search" value="<?= $this->search->getValue(); ?>"
                       placeholder="Pesquise numero de controle, acomodação ou cliente">
            </div>
            <div class="col-lg-12">
                <i>Digite um intervalo de datas de check-out.</i>
            </div>
            <div class="input-group col-lg-5">
                <input type="text" class="form-control date" name="date1" value="<?= $this->date1->getValue(); ?>">
            </div>
            <div class="input-group col-lg-5">
                <input type="text" class="form-control date" name="date2" value="<?= $this->date2->getValue(); ?>">
            </div>
            <div class="input-group col-lg-2">
            <span class="input-group-btn">
                <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-search"></span></button>
            </span>
            </div>
        </div>
    </form>

    <hr>

    <table class="table table-bordered table-hover">
        <thead>
        <th>Cód. Controle</th>
        <th>Acomodação</th>
        <th>Cliente</th>
        <th>Check-in</th>
        <th class="warning">Check-out</th>
        <th class="col-lg-3">Ações</th>
        </thead>
        <?php
        if ($this->accommodations):
            foreach ($this->accommodations as $accommodation): ?>

                <tr>
                    <td><?= $accommodation['control']; ?></td>
                    <td>
                        <?=
                        link_to($rooms_show_path($accommodation['room_id']),
                            $accommodation['room_number']); ?>
                    </td>
                    <td>
                        <?=
                        link_to($clients_show_path($accommodation['client_id']),
                            $accommodation['client_name']); ?>
                    </td>
                    <td><?= format_date($accommodation['check_in'], 'd/m/Y H:i:s'); ?></td>
                    <td><?= format_date($accommodation['check_out'], 'd/m/Y H:i:s'); ?></td>
                    <td class="col-md-3">
                        <?= link_to($accommodations_show_path($accommodation['accommodation_id']), 'detalhes'); ?> |
                        <?= link_to($accommodations_payment_path($accommodation['accommodation_id']), 'pagamento'); ?>
                    </td>
                </tr>

            <?php
            endforeach; ?>
            <tfoot>
            <td colspan="6"><?= count($this->accommodations); ?> registro(s) encontrado(s)</td>
            </tfoot>
        <?php else: ?>
            <tr>
                <td colspan="6"><span class="label label-info">Nenhum registro encontrado!</span></td>
            </tr>
        <?php endif; ?>
    </table>
</div>