<div class="page-header">
    <h2>Hospedagem - pagamento</h2>
</div>

<div class="col-lg-3">
    <ul class="nav nav-pills nav-stacked">
        <li><?= link_to($accommodations_index_path(), "Hóspedes <span class='badge'>{$this->accounting}</span>"); ?></li>
        <li><?=
            link_to($accommodations_check_out_path($this->accommodation->id->getValue()),
                'Check-out', 'data-confirm="Tem certeza?"'); ?></li>
    </ul>
</div>

<div class="col-lg-7">

    <h3>Acomodação</h3>

    <table class="table">
        <tr>
            <td class="col-lg-4"><b>Acomodação:</b></td>
            <td><?=
                link_to($rooms_show_path($this->reservation['rooms']['id']),
                    $this->reservation['rooms']['number']); ?></td>
        </tr>
        <tr>
            <td class="col-lg-4"><b>Valor da diária:</b></td>
            <td><?= real_format($this->reservation['rooms']['price']); ?></td>
        <tr>

    </table>

    <h3>Sobre a reserva</h3>

    <table class="table">
        <tr>
            <td class="col-lg-4"><b>Criado em:</b></td>
            <td><?= format_date($this->reservation['reservations']['created_at'], 'd/m/Y H:i:s'); ?></td>
        </tr>

        <tr>
            <td><b>Cliente:</b></td>
            <td><?=
                link_to($clients_show_path($this->reservation['clients']['id']),
                    $this->reservation['clients']['name']); ?></td>
        </tr>
        <tr>
            <td><b>Funcionário:</b></td>
            <td><?=
                link_to($employees_show_path($this->reservation['employees']['id']),
                    $this->reservation['employees']['name']); ?></td>
        </tr>
        <tr>
            <td><b>Data da reserva:</b></td>
            <td><?= format_date($this->reservation['reservations']['date_reserve'], 'd/m/Y H:i:s'); ?></td>
        </tr>
        <tr>
            <td><b>Data da previsão de saída:</b></td>
            <td><?= format_date($this->reservation['reservations']['date_prevision'], 'd/m/Y H:i:s'); ?></td>
        </tr>
    </table>

    <br>

    <h3>Sobre a hospedagem</h3>
    <table class="table">
        <tr>
            <td class="col-lg-4"><b>Check-in:</b></td>
            <td><?= format_date($this->accommodation->check_in->getValue(), 'd/m/Y H:i:s'); ?></td>
        </tr>
        <tr>
            <td class="col-lg-4"><b>Check-out:</b></td>
            <td><?= format_date($this->accommodation->check_out->getValue(), 'd/m/Y H:i:s'); ?></td>
        </tr>
    </table>

    <br>

    <h3>Serviços</h3>
    <table class="table table-bordered">
        <thead>
        <th>Tipo</th>
        <th>Nota</th>
        <th>Data</th>
        </thead>
        <? if ($this->services): ?>
            <? foreach ($this->services as $service): ?>
                <tr>
                    <td><?= $service['service_type_description']; ?></td>
                    <td><?= $service['service_note']; ?></td>
                    <td><?= format_date($service['service_created_at'], 'd/m/Y H:i:s'); ?></td>
                </tr>
            <? endforeach; ?>
        <? else: ?>
            <tr>
                <td colspan="2">
                    <span class="label label-info">Nenhum serviço encontrado!</span>
                </td>
            </tr>
        <? endif; ?>
    </table>

</div>