<div class="page-header" id="page-title">
    <h2>Hospedagem - detalhes</h2>
</div>

<div class="col-lg-3">
    <ul class="nav nav-pills nav-stacked">
        <li><?= link_to($accommodations_index_path(), "Hóspedes <span class='badge'>{$this->accounting}</span>"); ?></li>
        <?php if( $this->accommodation->check_out->getValue() == ''):?>
        <li><?=
            link_to($accommodations_check_out_path($this->accommodation->id->getValue()),
                'Check-out', 'data-confirm="Tem certeza?"'); ?></li>
        <? endif; ?>
        <li><?=
            link_to($accommodations_payment_path($this->accommodation->id->getValue()),
                'Pagamento'); ?></li>
    </ul>
</div>

<div class="col-lg-7">


    <h3>Sobre a hospedagem</h3>
    <table class="table">
        <tr>
            <td class="col-lg-4"><b>Código de controle:</b></td>
            <td><?= $this->accommodation->control->getValue(); ?></td>
        </tr><tr>
            <td class="col-lg-4"><b>Check-in:</b></td>
            <td><?= format_date($this->accommodation->check_in->getValue(), 'd/m/Y H:i:s'); ?></td>
        </tr>
        <tr>
            <td class="col-lg-4"><b>Check-out:</b></td>
            <td><?= format_date($this->accommodation->check_out->getValue(), 'd/m/Y H:i:s'); ?></td>
        </tr>
    </table>

    <br>

    <h3>Sobre a reserva</h3>

    <table class="table">
        <tr>
            <td class="col-lg-4"><b>Criado em:</b></td>
            <td><?= format_date($this->reservation['reservations']['created_at'], 'd/m/Y H:i:s'); ?></td>
        </tr>
        <tr>
            <td><b>Acomodação:</b></td>
            <td><?=
                link_to($rooms_show_path($this->reservation['rooms']['id']),
                    $this->reservation['rooms']['number']); ?></td>
        <tr>
        <tr>
            <td><b>Cliente:</b></td>
            <td><?=
                link_to($clients_show_path($this->reservation['clients']['id']),
                    $this->reservation['clients']['name']); ?></td>
        <tr>
        <tr>
            <td><b>Funcionário:</b></td>
            <td><?=
                link_to($employees_show_path($this->reservation['employees']['id']),
                    $this->reservation['employees']['name']); ?></td>
        <tr>
        <tr>
            <td><b>Data da previsão de check-in:</b></td>
            <td><?= format_date($this->reservation['reservations']['prevision_check_in'], 'd/m/Y H:i:s'); ?></td>
        <tr>
        <tr>
            <td><b>Data da previsão de check-out:</b></td>
            <td><?= format_date($this->reservation['reservations']['prevision_check_out'], 'd/m/Y H:i:s'); ?></td>
        <tr>
    </table>


</div>