<div class="page-header" id="page-title">
    <h2>Editar Cliente</h2>
</div>

<div class="col-lg-3">
    <ul class="nav nav-pills nav-stacked">
        <li><?= link_to($clients_index_path(), 'Lista de Clientes'); ?></li>
        <li><?= link_to($clients_destroy_path($this->client->id->getValue()), 'Excluir', 'data-confirm="Tem certeza?"'); ?></li>
    </ul>
</div>

<div class="col-lg-7">

    <form role="form" action="<?=$clients_update_path($this->client->id->getValue())?>" method="POST">

        <?=text_field($this->client->name, array('name'=>'client', 'title'=>'Nome', 'placeholder'=>'Nome...')); ?>
        <?=text_field($this->client->cpf, array('name'=>'client', 'title'=>'CPF', 'class' => 'cpf')); ?>
        <?=text_field($this->client->rg, array('name'=>'client', 'title'=>'RG')); ?>
        <?=select($this->client->enterprise_id, $this->enterprises,
            array('name'=>'client', 'title'=>'Empresa'),$this->client->enterprise_id->getValue()); ?>
        <?=text_field($this->client->birth, [ 'name'=>'client', 'title'=>'Nascimento', 'class' => 'date' ]); ?>

        <button type="submit" class="btn btn-primary"> Confirmar</button>
    </form>

</div>