<div class="page-header">
    <h2>Cliente</h2>
</div>

<div class="col-lg-3">
    <ul class="nav nav-pills nav-stacked">
        <li><?= link_to($clients_index_path(), 'Lista de Clientes'); ?></li>
        <li><?= link_to($clients_fresh_path(), 'Novo Cliente'); ?></li>
        <li><?= link_to($clients_edit_path($this->client['clients']['id']), 'Editar'); ?></li>
        <li><?= link_to($clients_destroy_path($this->client['clients']['id']), 'Excluir', 'data-confirm="Tem certeza?"'); ?></li>
    </ul>
</div>

<div class="col-lg-7">

    <table class="table">
        <tr>
            <td class="col-lg-4"><b>Criado em:</b></td>
            <td><?= format_date($this->client['clients']['created_at']); ?></td>
        </tr>
        <tr>
            <td><b>Nome:</b></td>
            <td><?= $this->client['clients']['name'] ?></td>
        <tr>
        <tr>
            <td><b>CPF:</b></td>
            <td><?= $this->client['clients']['cpf'] ?></td>
        <tr>
        <tr>
            <td><b>RG:</b></td>
            <td><?= $this->client['clients']['rg'] ?></td>
        <tr>
        <tr>
            <td><b>Empresa:</b></td>
            <td><?=link_to($enterprises_show_path(@$this->client['enterprises']['id']),
                @$this->client['enterprises']['name']); ?></td>
        </tr>
        <tr>
            <td><b>Data de Nascimento:</b></td>
            <td><?= format_date($this->client['clients']['birth'], 'd/m/Y'); ?></td>
        </tr>
    </table>

</div>