<div class="page-header" id="page-title">
    <h2>Editar Motivo</h2>
</div>

<div class="col-lg-3">
    <ul class="nav nav-pills nav-stacked">
        <li><?= link_to($reasons_index_path(), 'Lista de motivos'); ?></li>
        <li><?= link_to($reasons_destroy_path($this->reason->id->getValue()), 'Excluir', 'data-confirm="Tem certeza?"'); ?></li>
    </ul>
</div>

<div class="col-lg-7">

    <form role="form" action="<?=$reasons_edit_path($this->reason->id->getValue())?>" method="POST">

        <?=text_area($this->reason->description, array('name'=>'reason', 'title'=>'Descrição', 'placeholder'=>'Descrição')); ?>

        <button type="submit" class="btn btn-primary"> Confirmar</button>
    </form>

</div>