<div class="page-header">
    <h2>Novo Motivo</h2>
</div>

<div class="col-lg-3">
    <ul class="nav nav-pills nav-stacked">
        <li><?= link_to($reasons_index_path(), 'Lista de motivos'); ?></li>
    </ul>
</div>

<div class="col-lg-7">

    <form role="form" action="<?= $reasons_create_path() ?>" method="POST">

        <?=text_area($this->reason->description, array('name'=>'reason', 'title'=>'Descrição', 'placeholder'=>'Descrição')); ?>

        <button type="submit" class="btn btn-primary"> Confirmar</button>
    </form>

</div>