<div class="page-header">
    <h1>Motivos</h1>
</div>

<div class="col-lg-3">
    <ul class="nav nav-pills nav-stacked">
        <li><?= link_to($reasons_fresh_path(), 'Novo motivo'); ?></li>
    </ul>
</div>

<div class="col-lg-7">
    <table class="table table-bordered">
        <tr>
            <th>#</th>
            <th>Descrição</th>
            <th>Ação</th>
        </tr>
        <?php
        $n = 1;
        if ( $this->reasons ):
            foreach ($this->reasons as $reason): ?>

                <tr>
                    <td><?= $n; ?></td>
                    <td><?= $reason['description']; ?></td>
                    <td class="col-md-3">
                        <?= link_to( $reasons_show_path($reason['id']), 'ver'); ?>|
                        <?= link_to( $reasons_edit_path($reason['id']), 'editar'); ?>|
                        <?= link_to( $reasons_destroy_path($reason['id']), 'remover','data-confirm="Tem certeza?"'); ?>
                    </td>
                </tr>

                <?php
                $n++;
            endforeach; else: ?>
            <tr>
                <td colspan="3"><span class="label label-info">Nenhum registro encontrado!</span></td>
            </tr>
        <?php endif; ?>
    </table>
</div>