<div class="page-header">
    <h2>Motivo</h2>
</div>

<div class="col-lg-3">
    <ul class="nav nav-pills nav-stacked">
        <li><?= link_to($reasons_index_path(), 'Lista de motivos'); ?></li>
        <li><?= link_to($reasons_fresh_path(), 'Novo motivo'); ?></li>
        <li><?= link_to($reasons_edit_path($this->reason->id->getValue()), 'Editar'); ?></li>
        <li><?= link_to($reasons_destroy_path($this->reason->id->getValue()), 'Excluir', 'data-confirm="Tem certeza?"'); ?></li>
    </ul>
</div>

<div class="col-lg-7">

    <h4>Descrição:</h4>
    <p><?=$this->reason->description->getValue(); ?></p>

</div>