<div class="page-header">
    <h2>Editar Tipo de Acomodação</h2>
</div>

<div class="col-lg-3">
    <ul class="nav nav-pills nav-stacked">
        <li><?= link_to($room_types_index_path(), 'Lista de Tipos de acomodações'); ?></li>
        <li><?= link_to($room_types_destroy_path($this->type->id->getValue()), 'Excluir', 'data-confirm="Tem certeza?"'); ?></li>
    </ul>
</div>

<div class="col-lg-7">

    <form role="form" action="<?=url_for($room_types_edit_path($this->type->id->getValue()))?>" method="POST">

        <?=text_field($this->type->title, array('name'=>'type', 'title'=>'Título', 'placeholder'=>'Título')); ?>
        <?=text_area($this->type->characteristics, array('name'=>'type', 'title'=>'Características', 'placeholder'=>'Características')); ?>
        <?=text_field($this->type->price, array('name'=>'type', 'title'=>'Preço', 'placeholder'=>'0,00')); ?>

        <button type="submit" class="btn btn-primary"> Confirmar</button>
    </form>

</div>