<?php if ($type != 'hidden'): ?>
    <div class="form-group has-<?= $field->getFlagError(); ?>">
    <label class="control-label" for="f_<?= $field->getName(); ?>"><?= $title; ?></label>
<?php endif; ?>
    <input
        type="<?= $type; ?>"
        <?= $field->isRequired() ? 'required="required"' : ''; ?>
        class="form-control <?= $class; ?>"
        name="<?= $no_array_name ? $name : $name . '[' . $field->getName() . ']'; ?>"
        <?php if( $field->getType() == 'datetime' ) $value = format_date($field->getValue(),'d/m/Y H:i:s');
            elseif( $field->getType() == 'date' ) $value = format_date($field->getValue(),'d/m/Y'); ?>
        value="<?= $value !== false ? $value : $field->getValue() ?>"
        id="f_<?= $field->getName(); ?>" placeholder="<?= $placeholder; ?>">
<?php if ($type != 'hidden'): ?>
    <p class="help-block" id="f_<?= $field->getName(); ?>_result"><?= $field->getError(); ?></p>
    </div>
<?php endif; ?>