<div class="page-header" id="page-title">
    <h1>Reservas - histórico</h1>
</div>

<div class="col-lg-3">
    <ul class="nav nav-pills nav-stacked">
        <li><?= link_to($reservations_index_path(), "Reservas <span class='badge'>{$this->countReservations}</span>"); ?></li>
    </ul>
</div>

<div class="col-lg-8">

    <form method="POST" action="<?= $reservations_history_path(); ?>">
        <div class="input-group">
            <input type="text" class="form-control" name="search" value="<?= $this->search->getValue(); ?>"
                   placeholder="Pesquise cliente, funcionário ou acomodação">
            <span class="input-group-btn">
                <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-search"></span></button>
            </span>
        </div>
    </form>

    <br>

    <table class="table table-bordered table-hover">
        <thead>
            <th>#</th>
            <th>Acomodação</th>
            <th>Cliente</th>
            <th>Data Reserva</th>
            <th>Previsão check-in</th>
            <th>Ação</th>
        </thead>
        <?php
        $n = 1;
        if ($this->reservations):
            foreach ($this->reservations as $reservation): ?>

                <tr>
                    <td><?= $n; ?></td>
                    <td>
                        <?=
                        link_to($rooms_show_path($reservation['room_id']),
                            $reservation['room_number']); ?>
                    </td>
                    <td>
                        <?=
                        link_to($clients_show_path($reservation['client_id']),
                            $reservation['client_name']); ?>
                    </td>
                    <td><?= format_date($reservation['date_reserve'],'d/m/Y H:i:s'); ?></td>
                    <td><?= format_date($reservation['prevision_check_in'], 'd/m/Y H:i:s'); ?></td>
                    <td class="col-md-1">
                        <?= link_to($reservations_show_path($reservation['reservation_id']), 'ver'); ?>
                    </td>
                </tr>

                <?php
                $n++;
            endforeach; ?>
            <tfoot>
                <td colspan="6"><?=count($this->reservations); ?> registro(s) encontrado(s)</td>
            </tfoot>
        <?php else: ?>
            <tr>
                <td colspan="7"><span class="label label-info">Nenhum registro encontrado!</span></td>
            </tr>
        <?php endif; ?>
    </table>
</div>