<div class="page-header">
    <h1>Reservas ativas</h1>
</div>

<div class="col-lg-3">
    <ul class="nav nav-pills nav-stacked">
        <li><?= link_to($reservations_fresh_path(), 'Nova reserva'); ?></li>
        <li><?= link_to($accommodations_index_path(), "Hóspedes <span class='badge'>{$this->guests}</span>"); ?></li>
    </ul>
</div>

<div class="col-lg-8">
    <table class="table table-bordered table-hover">
        <thead>
            <th>#</th>
            <th>Acomodação</th>
            <th>Cliente</th>
            <th>Motivo</th>
            <th>Data Reserva</th>
            <th>Data Previsão</th>
            <th>Ações</th>
        </thead>
        <?php
        $n = 1;
        if ($this->reservations):
            foreach ($this->reservations as $reservation): ?>

                <tr>
                    <td><?= $n; ?></td>
                    <td>
                        <?=
                        link_to($rooms_show_path($reservation['room_id']),
                            $reservation['room_number']); ?>
                    </td>
                    <td>
                        <?=
                        link_to($clients_show_path($reservation['client_id']),
                            $reservation['client_name']); ?>
                    </td>
                    <td>
                        <?=
                        link_to(@$reasons_show_path($reservation['reason_id']),
                            @$reservation['reason_description']); ?>
                    </td>
                    <td><?= format_date($reservation['date_reserve'],'d/m/Y H:i:s'); ?></td>
                    <td><?= format_date($reservation['date_prevision'], 'd/m/Y H:i:s'); ?></td>
                    <td class="col-md-3">
                        <?= link_to($reservations_show_path($reservation['reservation_id']), 'ver'); ?>|
                        <?= link_to($reservations_check_in_path($reservation['reservation_id']), 'check-in',
                            'data-confirm="Tem certeza?"'); ?>|
                        <?=link_to($reservations_cancel_path($reservation['reservation_id']), 'cancelar',
                            'data-confirm="Tem certeza?"'); ?>
                    </td>
                </tr>

                <?php
                $n++;
            endforeach; ?>
            <tfoot>
                <td colspan="7"><?=count($this->reservations); ?> registro(s) encontrado(s)</td>
            </tfoot>
        <?php else: ?>
            <tr>
                <td colspan="7"><span class="label label-info">Nenhum registro encontrado!</span></td>
            </tr>
        <?php endif; ?>
    </table>
</div>