
<div class="page-header">
    <h2>Reserva de <?=format_date($this->reservation['reservations']['created_at'],'d/m/Y H:i:s'); ?></h2>
</div>

<div class="col-lg-3">
    <ul class="nav nav-pills nav-stacked">
        <li><?= link_to($reservations_index_path(), "Reservas <span class='badge'>{$this->accounting}</span>"); ?></li>
        <li><?= link_to($reservations_fresh_path(), 'Nova reserva'); ?></li>
        <li><?= link_to($reservations_check_in_path($this->reservation['reservations']['id']),
                'Check-in', 'data-confirm="Tem certeza?"'); ?></li>
        <li><?= link_to($reservations_cancel_path($this->reservation['reservations']['id']),
                'Cancelar', 'data-confirm="Tem certeza?"'); ?></li>
    </ul>
</div>

<div class="col-lg-7">

    <table class="table">
        <tr>
            <td class="col-lg-4"><b>Criado em:</b></td>
            <td><?= format_date($this->reservation['reservations']['created_at'], 'd/m/Y H:i:s'); ?></td>
        </tr>
        <tr>
            <td><b>Acomodação:</b></td>
            <td><?=
                link_to($rooms_show_path($this->reservation['rooms']['id']),
                    $this->reservation['rooms']['number']); ?></td>
        </tr>
        <tr>
            <td><b>Cliente:</b></td>
            <td><?=
                link_to($clients_show_path($this->reservation['clients']['id']),
                    $this->reservation['clients']['name']); ?></td>
        </tr>
        <tr>
            <td><b>Funcionário:</b></td>
            <td><?=
                link_to($employees_show_path($this->reservation['employees']['id']),
                    $this->reservation['employees']['name']); ?></td>
        </tr>
        <tr>
            <td><b>Data da previsão de check-in:</b></td>
            <td><?=format_date($this->reservation['reservations']['prevision_check_in'],'d/m/Y H:i:s'); ?></td>
        </tr>
        <tr>
            <td><b>Data da previsão de check-out:</b></td>
            <td><?=format_date($this->reservation['reservations']['prevision_check_out'],'d/m/Y H:i:s'); ?></td>
        </tr>
    </table>

</div>