<div class="page-header" id="page-title">
    <h2>Editar Acomodações</h2>
</div>

<div class="col-lg-3">
    <ul class="nav nav-pills nav-stacked">
        <li><?= link_to($rooms_index_path(), 'Lista de Acomodações'); ?></li>
        <li><?= link_to($rooms_destroy_path($this->room->id->getValue()), 'Excluir', 'data-confirm="Tem certeza?"'); ?></li>
    </ul>
</div>

<div class="col-lg-7">

    <form role="form" action="<?=$rooms_update_path($this->room->id->getValue())?>" method="POST">

        <?=select($this->room->room_type_id, $this->types,
            ['name'=>'room', 'title'=>'Categoria'], $this->room->room_type_id->getValue()); ?>
        <?=text_field($this->room->number, array('name'=>'room', 'title'=>'Número', 'placeholder'=>'X')); ?>
        <?=text_field($this->room->floor, array('name'=>'room', 'title'=>'Andar', 'placeholder'=>'Ex: 1')); ?>
        <?=text_field($this->room->price, array('name'=>'room', 'title'=>'Preço', 'placeholder'=>'0,00')); ?>
        <?=text_area($this->room->description, array('name'=>'room', 'title'=>'Descrição', 'placeholder'=>'descrição...')); ?>

        <button type="submit" class="btn btn-primary"> Confirmar</button>
    </form>

</div>