<div class="page-header">
    <h2>Nova Acomodação</h2>
</div>

<div class="col-lg-3">
    <ul class="nav nav-pills nav-stacked">
        <li><?= link_to($rooms_index_path(), 'Lista de Acomodações'); ?></li>
    </ul>
</div>

<div class="col-lg-7">

    <form role="form" action="<?=$rooms_fresh_path(); ?>" method="POST">

        <?=select($this->room->room_type_id, $this->types, ['name'=>'room', 'title'=>'Tipo'] ); ?>
        <?=text_field($this->room->number, array('name'=>'room', 'title'=>'Número', 'placeholder'=>'X')); ?>
        <?=text_field($this->room->floor, array('name'=>'room', 'title'=>'Andar', 'placeholder'=>'Ex: 1')); ?>
        <?=text_area($this->room->description, array('name'=>'room', 'title'=>'Descrição', 'placeholder'=>'descrição...')); ?>

        <button type="submit" class="btn btn-primary"> Confirmar</button>
    </form>

</div>