<div class="page-header">
    <h2>Novo Produto</h2>
</div>

<div class="col-lg-3">
    <ul class="nav nav-pills nav-stacked">
        <li><?= link_to($products_index_path(), 'Lista de Produtos'); ?></li>
    </ul>
</div>

<div class="col-lg-7">

    <form role="form" action="<?=$products_fresh_path(); ?>" method="POST">

        <?=text_area($product->description, ['name'=>'product', 'title'=>'Descrição', 'placeholder'=>'Descrição']); ?>
        <?=text_field($product->price, ['name'=>'product', 'title'=>'Valor (R$)', 'placeholder'=>'0,00']); ?>
        <?=select($product->product_type_id, $types, ['name'=>'product', 'title'=>'Categoria']); ?>

        <button type="submit" class="btn btn-primary"> Confirmar</button>
    </form>

</div>